sudo: required
services:
  - docker

before_install:
  - docker build -t unlmtd/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true unlmtd/react-test npm test -- --coverage

after_success:
  - docker build -t unlmtd/multi-client ./client
  - docker build -t unlmtd/multi-nginx ./nginx
  - docker build -t unlmtd/multi-server ./server
  - docker build -t unlmtd/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to the docker hub
  - docker push unlmtd/multi-client
  - docker push unlmtd/multi-nginx
  - docker push unlmtd/multi-server
  - docker push unlmtd/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker-2
  env: MultiDocker2-env
  bucket_name: elasticbeanstalk-eu-central-1-012153171837
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
